- filename: D20241112-T035837.raw
  metadata_start_time: '2024-11-12T03:58:37'
  first_ping_time: '2024-11-12T03:58:37.910+00:00'
  last_ping_time: '2024-11-12T04:53:13.921+00:00'
  raw3_count: 16380
  gps_data:
    first_gps:
      latitude: 41.520534
      longitude: -71.344097
      timestamp: '2024-11-12T03:58:37.910706+00:00'
      nmea_sentence: $INGGA,040021.083,4131.23203,N,07120.64584,W,2,32,1.0,-0.34,M,,,7,0131
    last_gps:
      latitude: 41.520697
      longitude: -71.344159
      timestamp: '2024-11-12T04:53:14.129128+00:00'
      nmea_sentence: $INGGA,045457.084,4131.24181,N,07120.64951,W,2,35,0.8,-0.24,M,,,7,0131
    nmea_count: 85195
    valid_gps_count: 3277
    sentence_types:
    - INGGA
  channels:
  - channel_id: WBT 400479-15 ES18_ES
    transceiver_id: '400479'
    transceiver_model: WBT
    transceiver_ethernet_address: 009072061c5f
    transceiver_serial_number: '400479'
    transceiver_number: 1
    transceiver_port: 15
    channel_instance_number: 1
    multiplexing_found: false
    transducer_serial_number: null
    transducer_model: ES18
    frequency: 18000.0
    nominal_transducer_frequency: 18000.0
    transmit_duration_nominal: 0.001024
    transmit_power: 1000.0
    pulse_form: '0'
    frequency_start: 18000.0
    frequency_end: 18000.0
  - channel_id: WBT 400528-15 ES38-7_ES
    transceiver_id: '400528'
    transceiver_model: WBT
    transceiver_ethernet_address: 009072061c90
    transceiver_serial_number: '400528'
    transceiver_number: 2
    transceiver_port: 15
    channel_instance_number: 1
    multiplexing_found: false
    transducer_serial_number: '447'
    transducer_model: ES38-7
    frequency: 38000.0
    nominal_transducer_frequency: 38000.0
    transmit_duration_nominal: 0.001024
    transmit_power: 1000.0
    pulse_form: '0'
    frequency_start: 38000.0
    frequency_end: 38000.0
  - channel_id: WBT 400503-15 ES70-7C_ES
    transceiver_id: '400503'
    transceiver_model: WBT
    transceiver_ethernet_address: 009072061c77
    transceiver_serial_number: '400503'
    transceiver_number: 3
    transceiver_port: 15
    channel_instance_number: 1
    multiplexing_found: false
    transducer_serial_number: null
    transducer_model: ES70-7C
    frequency: 70000.0
    nominal_transducer_frequency: 70000.0
    transmit_duration_nominal: 0.001024
    transmit_power: 750.0
    pulse_form: '0'
    frequency_start: 70000.0
    frequency_end: 70000.0
  - channel_id: WBT 400517-15 ES120-7C_ES
    transceiver_id: '400517'
    transceiver_model: WBT
    transceiver_ethernet_address: 009072061c85
    transceiver_serial_number: '400517'
    transceiver_number: 4
    transceiver_port: 15
    channel_instance_number: 1
    multiplexing_found: false
    transducer_serial_number: null
    transducer_model: ES120-7C
    frequency: 120000.0
    nominal_transducer_frequency: 120000.0
    transmit_duration_nominal: 0.001024
    transmit_power: 250.0
    pulse_form: '0'
    frequency_start: 120000.0
    frequency_end: 120000.0
  - channel_id: WBT 400509-15 ES200-7C_ES
    transceiver_id: '400509'
    transceiver_model: WBT
    transceiver_ethernet_address: 009072061c7d
    transceiver_serial_number: '400509'
    transceiver_number: 5
    transceiver_port: 15
    channel_instance_number: 1
    multiplexing_found: false
    transducer_serial_number: null
    transducer_model: ES200-7C
    frequency: 200000.0
    nominal_transducer_frequency: 200000.0
    transmit_duration_nominal: 0.001024
    transmit_power: 150.0
    pulse_form: '0'
    frequency_start: 200000.0
    frequency_end: 200000.0
  file_format: EK80
  instrument: EK80
- filename: D20241112-T052842.raw
  metadata_start_time: '2024-11-12T05:28:42'
  first_ping_time: '2024-11-12T05:28:42.730+00:00'
  last_ping_time: '2024-11-12T05:54:22.221+00:00'
  raw3_count: 7700
  gps_data:
    first_gps:
      latitude: 41.520675
      longitude: -71.344127
      timestamp: '2024-11-12T05:28:42.730656+00:00'
      nmea_sentence: $INGGA,053026.086,4131.24052,N,07120.64764,W,2,31,0.8,0.30,M,,,7,0131
    last_gps:
      latitude: 41.520657
      longitude: -71.344105
      timestamp: '2024-11-12T05:54:22.115092+00:00'
      nmea_sentence: $INGGA,055605.087,4131.23945,N,07120.64633,W,2,31,0.8,-0.44,M,,,4,0131
    nmea_count: 40036
    valid_gps_count: 1540
    sentence_types:
    - INGGA
  channels:
  - channel_id: WBT 400479-15 ES18_ES
    transceiver_id: '400479'
    transceiver_model: WBT
    transceiver_ethernet_address: 009072061c5f
    transceiver_serial_number: '400479'
    transceiver_number: 1
    transceiver_port: 15
    channel_instance_number: 1
    multiplexing_found: false
    transducer_serial_number: null
    transducer_model: ES18
    frequency: 18000.0
    nominal_transducer_frequency: 18000.0
    transmit_duration_nominal: 0.001024
    transmit_power: 1000.0
    pulse_form: '0'
    frequency_start: 18000.0
    frequency_end: 18000.0
  - channel_id: WBT 400528-15 ES38-7_ES
    transceiver_id: '400528'
    transceiver_model: WBT
    transceiver_ethernet_address: 009072061c90
    transceiver_serial_number: '400528'
    transceiver_number: 2
    transceiver_port: 15
    channel_instance_number: 1
    multiplexing_found: false
    transducer_serial_number: '447'
    transducer_model: ES38-7
    frequency: 38000.0
    nominal_transducer_frequency: 38000.0
    transmit_duration_nominal: 0.001024
    transmit_power: 1000.0
    pulse_form: '0'
    frequency_start: 38000.0
    frequency_end: 38000.0
  - channel_id: WBT 400503-15 ES70-7C_ES
    transceiver_id: '400503'
    transceiver_model: WBT
    transceiver_ethernet_address: 009072061c77
    transceiver_serial_number: '400503'
    transceiver_number: 3
    transceiver_port: 15
    channel_instance_number: 1
    multiplexing_found: false
    transducer_serial_number: null
    transducer_model: ES70-7C
    frequency: 70000.0
    nominal_transducer_frequency: 70000.0
    transmit_duration_nominal: 0.001024
    transmit_power: 750.0
    pulse_form: '0'
    frequency_start: 70000.0
    frequency_end: 70000.0
  - channel_id: WBT 400517-15 ES120-7C_ES
    transceiver_id: '400517'
    transceiver_model: WBT
    transceiver_ethernet_address: 009072061c85
    transceiver_serial_number: '400517'
    transceiver_number: 4
    transceiver_port: 15
    channel_instance_number: 1
    multiplexing_found: false
    transducer_serial_number: null
    transducer_model: ES120-7C
    frequency: 120000.0
    nominal_transducer_frequency: 120000.0
    transmit_duration_nominal: 0.001024
    transmit_power: 250.0
    pulse_form: '0'
    frequency_start: 120000.0
    frequency_end: 120000.0
  - channel_id: WBT 400509-15 ES200-7C_ES
    transceiver_id: '400509'
    transceiver_model: WBT
    transceiver_ethernet_address: 009072061c7d
    transceiver_serial_number: '400509'
    transceiver_number: 5
    transceiver_port: 15
    channel_instance_number: 1
    multiplexing_found: false
    transducer_serial_number: null
    transducer_model: ES200-7C
    frequency: 200000.0
    nominal_transducer_frequency: 200000.0
    transmit_duration_nominal: 0.001024
    transmit_power: 150.0
    pulse_form: '0'
    frequency_start: 200000.0
    frequency_end: 200000.0
  file_format: EK80
  instrument: EK80
- filename: D20241112-T055441.raw
  metadata_start_time: '2024-11-12T05:54:41'
  first_ping_time: '2024-11-12T05:54:41.686+00:00'
  last_ping_time: '2024-11-12T06:13:28.666+00:00'
  raw3_count: 5640
  gps_data:
    first_gps:
      latitude: 41.520653
      longitude: -71.344102
      timestamp: '2024-11-12T05:54:41.686248+00:00'
      nmea_sentence: $INGGA,055625.087,4131.23919,N,07120.64613,W,2,31,0.8,-0.55,M,,,6,0131
    last_gps:
      latitude: 41.520655
      longitude: -71.344111
      timestamp: '2024-11-12T06:13:29.110226+00:00'
      nmea_sentence: $INGGA,061512.087,4131.23929,N,07120.64666,W,2,33,0.8,0.29,M,,,5,0131
    nmea_count: 29317
    valid_gps_count: 1128
    sentence_types:
    - INGGA
  channels:
  - channel_id: WBT 400479-15 ES18_ES
    transceiver_id: '400479'
    transceiver_model: WBT
    transceiver_ethernet_address: 009072061c5f
    transceiver_serial_number: '400479'
    transceiver_number: 1
    transceiver_port: 15
    channel_instance_number: 1
    multiplexing_found: false
    transducer_serial_number: null
    transducer_model: ES18
    frequency: 18000.0
    nominal_transducer_frequency: 18000.0
    transmit_duration_nominal: 0.001024
    transmit_power: 1000.0
    pulse_form: '0'
    frequency_start: 18000.0
    frequency_end: 18000.0
  - channel_id: WBT 400528-15 ES38-7_ES
    transceiver_id: '400528'
    transceiver_model: WBT
    transceiver_ethernet_address: 009072061c90
    transceiver_serial_number: '400528'
    transceiver_number: 2
    transceiver_port: 15
    channel_instance_number: 1
    multiplexing_found: false
    transducer_serial_number: '447'
    transducer_model: ES38-7
    frequency: 38000.0
    nominal_transducer_frequency: 38000.0
    transmit_duration_nominal: 0.001024
    transmit_power: 1000.0
    pulse_form: '0'
    frequency_start: 38000.0
    frequency_end: 38000.0
  - channel_id: WBT 400503-15 ES70-7C_ES
    transceiver_id: '400503'
    transceiver_model: WBT
    transceiver_ethernet_address: 009072061c77
    transceiver_serial_number: '400503'
    transceiver_number: 3
    transceiver_port: 15
    channel_instance_number: 1
    multiplexing_found: false
    transducer_serial_number: null
    transducer_model: ES70-7C
    frequency: 70000.0
    nominal_transducer_frequency: 70000.0
    transmit_duration_nominal: 0.001024
    transmit_power: 750.0
    pulse_form: '0'
    frequency_start: 70000.0
    frequency_end: 70000.0
  - channel_id: WBT 400517-15 ES120-7C_ES
    transceiver_id: '400517'
    transceiver_model: WBT
    transceiver_ethernet_address: 009072061c85
    transceiver_serial_number: '400517'
    transceiver_number: 4
    transceiver_port: 15
    channel_instance_number: 1
    multiplexing_found: false
    transducer_serial_number: null
    transducer_model: ES120-7C
    frequency: 120000.0
    nominal_transducer_frequency: 120000.0
    transmit_duration_nominal: 0.001024
    transmit_power: 250.0
    pulse_form: '0'
    frequency_start: 120000.0
    frequency_end: 120000.0
  - channel_id: WBT 400509-15 ES200-7C_ES
    transceiver_id: '400509'
    transceiver_model: WBT
    transceiver_ethernet_address: 009072061c7d
    transceiver_serial_number: '400509'
    transceiver_number: 5
    transceiver_port: 15
    channel_instance_number: 1
    multiplexing_found: false
    transducer_serial_number: null
    transducer_model: ES200-7C
    frequency: 200000.0
    nominal_transducer_frequency: 200000.0
    transmit_duration_nominal: 0.001024
    transmit_power: 150.0
    pulse_form: '0'
    frequency_start: 200000.0
    frequency_end: 200000.0
  file_format: EK80
  instrument: EK80
- filename: D20241112-T061349.raw
  metadata_start_time: '2024-11-12T06:13:49'
  first_ping_time: '2024-11-12T06:13:49.866+00:00'
  last_ping_time: '2024-11-12T06:43:08.846+00:00'
  raw3_count: 8800
  gps_data:
    first_gps:
      latitude: 41.520657
      longitude: -71.34411
      timestamp: '2024-11-12T06:13:49.866734+00:00'
      nmea_sentence: $INGGA,061533.087,4131.23943,N,07120.64662,W,2,33,0.8,0.30,M,,,7,0131
    last_gps:
      latitude: 41.52069
      longitude: -71.344099
      timestamp: '2024-11-12T06:43:09.103738+00:00'
      nmea_sentence: $INGGA,064452.088,4131.24141,N,07120.64596,W,2,31,0.8,0.92,M,,,7,0131
    nmea_count: 45745
    valid_gps_count: 1760
    sentence_types:
    - INGGA
  channels:
  - channel_id: WBT 400479-15 ES18_ES
    transceiver_id: '400479'
    transceiver_model: WBT
    transceiver_ethernet_address: 009072061c5f
    transceiver_serial_number: '400479'
    transceiver_number: 1
    transceiver_port: 15
    channel_instance_number: 1
    multiplexing_found: false
    transducer_serial_number: null
    transducer_model: ES18
    frequency: 18000.0
    nominal_transducer_frequency: 18000.0
    transmit_duration_nominal: 0.001024
    transmit_power: 1000.0
    pulse_form: '0'
    frequency_start: 18000.0
    frequency_end: 18000.0
  - channel_id: WBT 400528-15 ES38-7_ES
    transceiver_id: '400528'
    transceiver_model: WBT
    transceiver_ethernet_address: 009072061c90
    transceiver_serial_number: '400528'
    transceiver_number: 2
    transceiver_port: 15
    channel_instance_number: 1
    multiplexing_found: false
    transducer_serial_number: '447'
    transducer_model: ES38-7
    frequency: 38000.0
    nominal_transducer_frequency: 38000.0
    transmit_duration_nominal: 0.001024
    transmit_power: 1000.0
    pulse_form: '0'
    frequency_start: 38000.0
    frequency_end: 38000.0
  - channel_id: WBT 400503-15 ES70-7C_ES
    transceiver_id: '400503'
    transceiver_model: WBT
    transceiver_ethernet_address: 009072061c77
    transceiver_serial_number: '400503'
    transceiver_number: 3
    transceiver_port: 15
    channel_instance_number: 1
    multiplexing_found: false
    transducer_serial_number: null
    transducer_model: ES70-7C
    frequency: 70000.0
    nominal_transducer_frequency: 70000.0
    transmit_duration_nominal: 0.001024
    transmit_power: 750.0
    pulse_form: '0'
    frequency_start: 70000.0
    frequency_end: 70000.0
  - channel_id: WBT 400517-15 ES120-7C_ES
    transceiver_id: '400517'
    transceiver_model: WBT
    transceiver_ethernet_address: 009072061c85
    transceiver_serial_number: '400517'
    transceiver_number: 4
    transceiver_port: 15
    channel_instance_number: 1
    multiplexing_found: false
    transducer_serial_number: null
    transducer_model: ES120-7C
    frequency: 120000.0
    nominal_transducer_frequency: 120000.0
    transmit_duration_nominal: 0.001024
    transmit_power: 250.0
    pulse_form: '0'
    frequency_start: 120000.0
    frequency_end: 120000.0
  - channel_id: WBT 400509-15 ES200-7C_ES
    transceiver_id: '400509'
    transceiver_model: WBT
    transceiver_ethernet_address: 009072061c7d
    transceiver_serial_number: '400509'
    transceiver_number: 5
    transceiver_port: 15
    channel_instance_number: 1
    multiplexing_found: false
    transducer_serial_number: null
    transducer_model: ES200-7C
    frequency: 200000.0
    nominal_transducer_frequency: 200000.0
    transmit_duration_nominal: 0.001024
    transmit_power: 150.0
    pulse_form: '0'
    frequency_start: 200000.0
    frequency_end: 200000.0
  file_format: EK80
  instrument: EK80
- filename: D20241112-T064333.raw
  metadata_start_time: '2024-11-12T06:43:33'
  first_ping_time: '2024-11-12T06:43:33.016+00:00'
  last_ping_time: '2024-11-12T06:43:33.016+00:00'
  raw3_count: 5
  gps_data:
    first_gps:
      latitude: 41.520692
      longitude: -71.344102
      timestamp: '2024-11-12T06:43:33.016770+00:00'
      nmea_sentence: $INGGA,064516.088,4131.24152,N,07120.64611,W,2,32,0.8,0.89,M,,,7,0131
    last_gps:
      latitude: 41.520692
      longitude: -71.344102
      timestamp: '2024-11-12T06:43:33.016770+00:00'
      nmea_sentence: $INGGA,064516.088,4131.24152,N,07120.64611,W,2,32,0.8,0.89,M,,,7,0131
    nmea_count: 14
    valid_gps_count: 1
    sentence_types:
    - INGGA
  channels:
  - channel_id: WBT 400479-15 ES18_ES
    transceiver_id: '400479'
    transceiver_model: WBT
    transceiver_ethernet_address: 009072061c5f
    transceiver_serial_number: '400479'
    transceiver_number: 1
    transceiver_port: 15
    channel_instance_number: 1
    multiplexing_found: false
    transducer_serial_number: null
    transducer_model: ES18
    frequency: 18000.0
    nominal_transducer_frequency: 18000.0
    transmit_duration_nominal: 0.001024
    transmit_power: 1000.0
    pulse_form: '0'
    frequency_start: 18000.0
    frequency_end: 18000.0
  - channel_id: WBT 400528-15 ES38-7_ES
    transceiver_id: '400528'
    transceiver_model: WBT
    transceiver_ethernet_address: 009072061c90
    transceiver_serial_number: '400528'
    transceiver_number: 2
    transceiver_port: 15
    channel_instance_number: 1
    multiplexing_found: false
    transducer_serial_number: '447'
    transducer_model: ES38-7
    frequency: 38000.0
    nominal_transducer_frequency: 38000.0
    transmit_duration_nominal: 0.001024
    transmit_power: 1000.0
    pulse_form: '0'
    frequency_start: 38000.0
    frequency_end: 38000.0
  - channel_id: WBT 400503-15 ES70-7C_ES
    transceiver_id: '400503'
    transceiver_model: WBT
    transceiver_ethernet_address: 009072061c77
    transceiver_serial_number: '400503'
    transceiver_number: 3
    transceiver_port: 15
    channel_instance_number: 1
    multiplexing_found: false
    transducer_serial_number: null
    transducer_model: ES70-7C
    frequency: 70000.0
    nominal_transducer_frequency: 70000.0
    transmit_duration_nominal: 0.001024
    transmit_power: 750.0
    pulse_form: '0'
    frequency_start: 70000.0
    frequency_end: 70000.0
  - channel_id: WBT 400517-15 ES120-7C_ES
    transceiver_id: '400517'
    transceiver_model: WBT
    transceiver_ethernet_address: 009072061c85
    transceiver_serial_number: '400517'
    transceiver_number: 4
    transceiver_port: 15
    channel_instance_number: 1
    multiplexing_found: false
    transducer_serial_number: null
    transducer_model: ES120-7C
    frequency: 120000.0
    nominal_transducer_frequency: 120000.0
    transmit_duration_nominal: 0.001024
    transmit_power: 250.0
    pulse_form: '0'
    frequency_start: 120000.0
    frequency_end: 120000.0
  - channel_id: WBT 400509-15 ES200-7C_ES
    transceiver_id: '400509'
    transceiver_model: WBT
    transceiver_ethernet_address: 009072061c7d
    transceiver_serial_number: '400509'
    transceiver_number: 5
    transceiver_port: 15
    channel_instance_number: 1
    multiplexing_found: false
    transducer_serial_number: null
    transducer_model: ES200-7C
    frequency: 200000.0
    nominal_transducer_frequency: 200000.0
    transmit_duration_nominal: 0.001024
    transmit_power: 150.0
    pulse_form: '0'
    frequency_start: 200000.0
    frequency_end: 200000.0
  file_format: EK80
  instrument: EK80
