"source_filenames": ["CalibrationDataFile-D20241112-T040149-038kHz.xml"]
"record_created": "2026-04-15T17:36:22.979236+00:00"
"record_author": "Placeholder Author"
"channel": "ES38-7 Serial No: 447 - Narrow"
"transceiver_id": "400528"
"transceiver_model": "TransceiverTypeWBT"
"transceiver_ethernet_address": "400528"
"transceiver_serial_number": "400528"
"transceiver_number": null
"transceiver_port": null
"channel_instance_number": 1
"transducer_model": "ES38-7"
"transducer_serial_number": "447"
"pulse_form": "0"
"frequency_start": 38000.0
"frequency_end": 38000.0
"nominal_transducer_frequency": 38000.0
"transmit_power": 1000.0
"transmit_duration_nominal": 0.001024
"multiplexing_found": null
"calibration_date": "2024-11-12"
"calibration_comments": "\n    "
"calibration_version": null
"absorption_indicative": 0.008958
"sound_speed_indicative": 1492.36
"temperature": 12.0
"salinity": 32.0
"acidity": 8.0
"pressure": null
"sample_interval": 4.8e-05
"transmit_bandwidth": 0.0
"beam_type": "BeamTypeSplit3CN"
"calibration_acquisition_method": null
"sphere_diameter": 38.1
"sphere_material": "tungsten carbide"
"source_file_type": ".xml"
"source_file_location": null
"sonar_software_version": "23.6.0.0"
"sonar_software_name": "EK80"
"equivalent_beam_angle": -20.7
"gain_correction": [26.82]
"sa_correction": [-0.1825]
"frequency": [38000.0]
"beamwidth_transmit_major": [6.84]
"beamwidth_receive_major": [6.84]
"beamwidth_transmit_minor": [6.52]
"beamwidth_receive_minor": [6.52]
"echoangle_major": [-0.15]
"echoangle_minor": [0.24]
"echoangle_major_sensitivity": null
"echoangle_minor_sensitivity": null
"source_file_paths": null
